### ISSUE TITLE
type mapping when fetching results

### ISSUE THREAD

**Issue by piccolbo** [s-u/RJDBC#19]
Question: I was wondering why in class.R line 295 and following you map all the return codes from 
.jcall(res@md, "I", "getColumnType", i)
to numeric() or character()

I traced through it and I saw that 16 is boolean, 12 is character, 4 is integer, 91 is date. Of course that may be true only for the database I am dealing with (spark SQL) and I may not be appreciating the challenge of getting this mapping right across JDBC implementations, but for my application mapping database types to the "closest" possible class in R would be better, particularly logical, integer and Date. The only loss of type information loading into the database that I could see, for atomic types, is for factor. 

Context:
 I am developing a package on top of SparkSQL and one of the tests is that if I load a data frame into a table and then fetch the table back, I get the same data. Of course one would have to set some limits on the col types and col names to make this work, but the goal is to make the "roundtrip" work under the weakest assumptions possible. 

Thanks

**Comment by s-u** [comment]
Databases historically only understand strings (a number was just a string like "123.456" that gets flagged as a number) so it is typically safe to resort to strings, but the slight issue is that string representation is slow in R, otherwise we could just always rely on strings. That's why the JDBC uses a compromise where it treats anything number-like as doubles (fast in R) and everything else as strings.

Part of the problem is that mapping of types is driver-specific, so relying on the minimal set of types increases compatibility.

Second issue is that there is no direct mapping of R types to SQL types. For example, there is no way to distinguish `character` from `factor` in SQL, so storing a `factor` will always lose information so there is no way to have a fully identical round-trip.

I agree that it would be possible to support at least some SQL92 special types like `TIMESTAMP` by simply running `fastPOSIXct()` or similar on the string obtained. So it may be worth-while to add a post-process step after teh result is retrieved into R before the data framer is returned to the user. Note, however, that this still doesn't solve the return-trip issues necessarily since it is in general impossible.

So, I'll keep this open for any suggestions on what conversions could be useful to users.

**Comment by s-u** [comment]
1c6399c adds some support for arbitrary post-processing, currently the default is to handle `DATE`, `DATETIME` and `TIMESTAMP`.
