### ISSUE TITLE
Error in .jfindClass(as.character(driverClass)[1]) : class not found

### ISSUE THREAD

**Issue by austintrombley** [s-u/RJDBC#26]
When I run the following statement (even though I explicitly name the directory to the jar file, it still doesn't find it

require(RJDBC)

.jaddClassPath("C:\Users\atrombley\Desktop\R\")
cassdrv <- JDBC("org.apache.cassandra.cql.jdbc.CassandraDriver",
                "C:\Users\atrombley\Desktop\R\cassandra-jdbc-1.2.5.jar")

Error in .jfindClass(as.character(driverClass)[1]) : class not found

**Comment by austintrombley** [comment]
I also posted here on stackoverflow so other's can help resolve this too:
http://stackoverflow.com/questions/32358528/rjdbc-cassandra-error-in-jfindclassas-characterdriverclass1-class-no

**Comment by MarcinKosinski** [comment]
Did you get an answer and can close this question?

**Comment by s-u** [comment]
Obviously, the example above won't work because of quoting issues (just use forward slashed instead of backslashes - saves you a lot of headaches). But, really, class issues are almost a FAQ - check the following:

 * unfortunately "class not found" is a misnomer. There are multiple reasons why a class cannot be loaded. Enable debug `.jclassLoader()$setDebug(1L)` so you can see the actual reason. Probably one of the most common reasons is JVM version mismatch - you can use `.J("java.lang.System")$getProperty("java.version")` to make sure you're running the version you think.
 * Cassandra drivers seems to have dependencies that are *not* included with the driver. Make sure you get those as well and that you add all the JAR files to the class path.

**Comment by austintrombley** [comment]
I never got an answer….

regards,
Austin D. Trombley, MBA
Senior Manager – Business Intelligence
cell:  415-767-6179
[cid:image001.png@01CFEA2B.2E127A90]<http://www.prosper.com/>

From: Marcin Kosiński
Reply-To: s-u/RJDBC
Date: Tuesday, January 19, 2016 at 3:12 AM
To: s-u/RJDBC
Cc: Austin Trombley
Subject: Re: [RJDBC] Error in .jfindClass(as.character(driverClass)[1]) : class not found (#26)


Did you get an answer and can close this question?

—
Reply to this email directly or view it on GitHub<https://github.com/s-u/RJDBC/issues/26#issuecomment-172820137>.





CONFIDENTIALITY STATEMENT: This email message, together with all attachments, is intended only for the individual or entity to which it is addressed and may contain legally privileged or confidential information. Any dissemination, distribution or copying of this communication by persons or entities other than the intended recipient, is strictly prohibited, and may be unlawful. If you have received this communication in error please contact the sender immediately and delete the transmitted material and all copies from your system, or if received in hard copy format, return the material to us via the United States Postal Service. Thank you.

**Comment by feng5** [comment]
i met this issue too
```
> drv <- JDBC("org.apache.hive.jdbc.HiveDriver", JDBC_DRIVER_PATH)
RJavaClassLoader: added '/opt/cloudera/parcels/CDH/lib/hive/lib/hive-jdbc-standalone.jar' to the URL class path loader
RJavaClassLoader: adding Java archive file '/opt/cloudera/parcels/CDH/lib/hive/lib/hive-jdbc-standalone.jar' to the internal class path
RJavaClassLoader: added '' to the URL class path loader
WARNING: the path '' does NOT exist, it will NOT be added to the internal class path!
RJavaClassLoader@7a4014a0.findClass(org.apache.hive.jdbc.HiveDriver)
Error in .jfindClass(as.character(driverClass)[1]) : class not found
> file.exists('/opt/cloudera/parcels/CDH/lib/hive/lib/hive-jdbc-standalone.jar')
[1] TRUE
```

**Comment by s-u** [comment]
See above. Note that Hive often requires *all* dependencies to be listed, not just the driver. That list is typically quite long (more than a dozen jars). Either way, please, read the documentation for your DB - this has really nothing to do with RDJBC itself.

**Comment by KKulma** [comment]
do Teradata drivers have multiple dependencies, too? I have same issues with Teradata (see [here](https://stackoverflow.com/questions/49132249/r-jdbc-not-finding-java-drivers-path-when-connecting-to-teradata))

**Comment by s-u** [comment]
No, you just have put in the wrong path (I responded in the SO)

**Comment by vanetoj1** [comment]
i m trying to connect RSTUDIO with athena and getting that error. did anyone ever figure out this error?

**Comment by s-u** [comment]
@vanetoj1 Generally, it means your class path is wrong or you didn't list all the dependencies. Since this is always driver-specific it's good to ask for support from whoever provides the driver.

Note that this error can also show up if your JDK is older than the driver requires, so always check the documentation for your driver.
