### ISSUE TITLE
dbBegin

### ISSUE THREAD

**Issue by fuerststat** [s-u/RJDBC#56]
dbCommit and dbRollback state that they work with dbBegin... but this seems not to be implemented jet?
how to work transactional instead?

**Comment by s-u** [comment]
Fair enough :) Both rollback and commit were implemented, but by default connections are in auto-commit mode, so the user would have to disable that first so that commit/rollback make sense. I have now added `dbBegin()` which disables the auto-commit mode thus making commit/rollback actually useful.
