### ISSUE TITLE
Unable to return decimal(17, 7) column automatically

### ISSUE THREAD

**Issue by MichaelChirico** [s-u/RJDBC#68]
Re-routing from the DBI issue tracker:

https://github.com/r-dbi/DBI/issues/247

I've got a table like this in `PrestoDB`:

```
dbGetQuery(my_conn, 'describe my_table')
#    Column          Type Extra Comment
# 1:     V1       integer              
# 2:     V2       varchar              
# 3:     V3 decimal(17,7)              
# 4:     V4     timestamp              
# 5:     V5     timestamp                   
```

I think that `DBI` doesn't know how to process the `decimal(17, 7)` column, `V3`:

```
dbGetQuery(my_conn, 'select V3 from my_table')
```
> Error in .jcall(rp, "I", "fetch", stride, block) : 

>   java.sql.SQLException: Value is not a number: java.lang.String

if I `cast(V3 as double)` it returns as expected; but `select * from my_table` in a database GUI, e.g. I use DBeaver, works as expected, no casting necessary, which is why I think this is a `DBI` bug. 

A more reproducible version (may require PrestoDB connection?)

```
dbGetQuery(my_conn, 'select cast(123.4356789 as decimal(17, 7)')
```

**Comment by s-u** [comment]
As the upstream discussion points out this looks like a bug in the driver - what claims to be a decimal (driver declares as numeric column type) is a string and fails to be retrieved as numeric. RJDBC is just a pass-through, so it uses whatever the driver supplies. The error comes from the driver - it claims a numeric type but doesn't support it, so that issue is not in RJDBC. The fact that some other tools works is irrelevant as those may coerce everything to string regardless of the type which is why it may not trigger the bug in the driver.

**Comment by krlmlr** [comment]
Would it be too far-fetched if _JDBC_ attempted to parse the string in this situation, or even if it just returned it as a character vector?

I wonder if `dbFetch()` (and therefore `dbGetQuery()`) should gain an option to specify expected data types.

**Comment by MichaelChirico** [comment]
Related? 

https://github.com/prestodb/presto/issues/11467

**Comment by dernst** [comment]
According to https://docs.oracle.com/javase/1.5.0/docs/guide/jdbc/getstart/mapping.html :
> The method recommended for retrieving DECIMAL and NUMERIC values is ResultSet.getBigDecimal. JDBC also allows access to these SQL types as simple Strings or arrays of char. Thus, Java programmers can use getString to receive a DECIMAL or NUMERIC result. However, this makes the common case where DECIMAL or NUMERIC are used for currency values rather awkward, since it means that application writers have to perform math on strings. It is also possible to retrieve these SQL types as any of the Java numeric types. 

Apparently returning `String` for `DECIMAL` columns is not wrong though but the driver should allow calling `getDouble` on the result set. DBeaver probably treats it in the preferred way via `getBigDecimal`.

**Comment by s-u** [comment]
Since this got bumped today - I think the only reasonable approach here would be to add a parameter to `fetch()` which allows to override the column types, so the user could force string type for columns that fail because of the driver. Alternatively, we could just add `string.only=TRUE` which would treat the entire table as strings to avoid issues with the user having to figure out all the column types in advance. After all, in the DB world everything is just a string anyway and all the number formats are faked in many databases. The only issue with that is that strings are by far the least efficient way on the R side so it wouldn't work for large data.

**Comment by yanqingfu** [comment]
@MichaelChirico Did you find a solution for this problem of `select *`

**Comment by yanqingfu** [comment]
@s-u where can I set `string.only=TRUE` ? in dbGetQuery function?

**Comment by yanqingfu** [comment]
I have another oracle database , and when using `driver = JDBC("oracle.jdbc.OracleDriver",classPath="/Users/670951/Desktop/ojdbc6.jar")` to do `select *`, no such java error

**Comment by MichaelChirico** [comment]
@yanqingfu `string.only=TRUE` is only being suggested as an option at this time IINM, i.e. not yet implemented.

You seem to also be using Presto and the Presto JDBC connector. In my own package I switched to using the REST connection; in fact the "officially supported" R package for Presto uses this I believe.
