### ISSUE TITLE
Segfault on macOS and Ubuntu

### ISSUE THREAD

**Issue by hrbrmstr** [s-u/RJDBC#71]
- macOS: R 3.5.2, RJDBC 0.2-7.1, rJava 0.9-10
- Ubuntu: R 3.5.3, RJDBC 0.2.7, rJava 0.9.10

I can make this:

```
Error in .jcall(rp, "I", "fetch", stride, block) :
  Java called System.exit(130) requesting R to quit - trying to recover

 *** caught segfault ***
address 0x78, cause 'memory not mapped'
```

or this:

```
Error in .jcall(s, "Ljava/sql/ResultSet;", "executeQuery", as.character(statement)[1],  : 
  Java called System.exit(130) requesting R to quit - trying to recover
```

happen on both macOS and Linux with the following code:

```r
library(rJava)
library(RJDBC)

JDBC(
  driverClass = "com.simba.athena.jdbc.Driver",
  classPath = "/usr/local/jars/AthenaJDBC42_2.0.6.jar",
  identifier.quote = '`'
) -> drv

dbConnect(
  drv = drv,
  "jdbc:awsathena://athena.us-east-1.amazonaws.com:443/sampledb",
  S3OutputLocation = "s3://aws-athena-query-results-569593279821-us-east-1",
  Schema = "sampledb",
  MaxErrorRetry = 10,
  ConnectTimeout = 10000,
  SocketTimeout = 10000,
  LogPath = "",
  LogLevel = 0,
  AwsCredentialsProviderClass = "com.simba.athena.amazonaws.auth.PropertiesFileCredentialsProvider",
  AwsCredentialsProviderArguments = "/home/bob/.aws/athenaCredentials.props"
) -> con

dbGetQuery(con, "SELECT * FROM elb_logs LIMIT 10")
```

And interrupting the script in the middle of the `dbGetQuery()` operation.

It happens in RStudio, terminal/console R, and R.app on macOS.

The code does require some minimal setup in Amazon Athena for others to reproduce.

I've tried to previous versions of the Athena JAR as well and none help resolve the problem.

**Comment by dernst** [comment]
Might be related to Java signal handlers, which should be disabled by default but may not be (see also https://github.com/s-u/rJava/pull/168)
Try adding -Xrs to your java.parameters, e.g. 
`options("java.parameters"=c("-Xmx10g", "-Xrs"))`
to see if you can still reproduce the problem.

**Comment by hrbrmstr** [comment]
ZOMGOSH #ty. That fixed it. 

What's weird is that this didn't happen "before" (i.e. I think this started happening after  R 3.5 b/c I _know_ I interrupted JDBC-based queries many times when running R 3.4.x and this never happened).

**Comment by hrbrmstr** [comment]
Is there a way for package authors to ensure this property is set on package load? I've got an RJDBC driver pkg for Athena (which is where this came from) and wld like to make it easier for users to avoid the crash scenario.

**Comment by s-u** [comment]
@dernst thanks for pointing to #168, you're right, this should be automatic, hopefully now fixed

**Comment by dernst** [comment]
I think that was introduced here: https://github.com/s-u/rJava/commit/ddff797516fc96f53903a9de8f6a4f5f0e551969#diff-67e997bcfdac55191033d57a16d1408a

If you really want to try and test for that, though there may be cases when it's legitimately disabled (see https://github.com/s-u/rJava/issues/63)
https://stackoverflow.com/questions/1490869/how-to-get-vm-arguments-from-inside-of-java-application
```
bean = .jcall("java/lang/management/ManagementFactory", "Ljava/lang/management/RuntimeMXBean;", "getRuntimeMXBean")
args = .jcall(bean, "Ljava/util/List;", "getInputArguments")
.jcall(args, "[Ljava/lang/Object;", "toArray")
```

**Comment by dernst** [comment]
thanks @s-u

**Comment by dkincaid** [comment]
I just ran into this same problem and the workaround is not working for me. It's still crashing. Surprisingly, it's not happening for me when I interrupt a query. It happens when I close the Shiny app. I'm building a Shiny app that just runs one query against Athena. Whenever I run it inside of RStudio when I exit the app I see a message that a Java application has called System.exit() and it's trying to recover. After a minute or two the RStudio session crashes.

**Comment by s-u** [comment]
When you see Java calling `System.exit()` it's rarely recoverable, because Java has been trying to kill the process. That's why the answer above has been to try to prevent Java from aborting the process. You may want to file this with RStudio since they may be in better position telling you what Shiny is doing at that point.

**Comment by dkincaid** [comment]
Thanks for the reply. The only thing in my app using Java is the Athena db package, so something in there must be doing it. I'll dig a little deeper into that and definitely file an issue over there. It looks so much like the error above that I assumed it was the same thing. Now I don't think it is.

**Comment by dernst** [comment]
@dkincaid 
Above error was because one of Java's signal handler tried to kill the process. To verify this is not the same problem try adding `-Xrs` to your `java.parameters` something like this before loading the JVM:
`options("java.parameters"=c("-Xmx3g", "-Xrs"))`
(this option should be set by default though so itp robably does nothing)
