### ISSUE TITLE
Intermittent connection error using RJDBC package while connecting to Oracle DB in R

### ISSUE THREAD

**Issue by doley25** [s-u/RJDBC#72]
Hi All

I am running a R script on Red Hat Linux machine which connects to an Oracle DB to fetch and write back data. The connection usually happens without any glitch most of the the time. I did not even get this issue till a year. But the same script now sometimes throws a connection error as below-

```
 **Error in .jcall("java/sql/DriverManager", "Ljava/sql/Connection;", "getConnection",  : 
  ignoring SIGPIPE signal**  
```

Not sure why i am getting this error after so many days of running the same script perfectly. Whats interesting is i cannot replicate the same error again, meaning after getting the error if i try running the script again - it gets connected and executes without any glitch.

Can someone explain why this might be happening and possibly a way around this?

`System info: OS - Linux (red hat), DB - Oracle db; R library used: RJDBC
`

**Comment by dernst** [comment]
`SIGPIPE` is the signal which is raised if you attempt to write to a closed socket connection. Longrunning TCP connections may get closed after a while depending on the configuration of both hosts, which might be the cause of the problem. Usually you would just ignore the error and try to reconnect. Oftentimes people set the signal handler to ignore which then causes an error in `write(2)` (et. al.). If you can I would attempt to intercept the error and just retry the DB operation you were trying to do.

**Comment by doley25** [comment]
@dernst : Thank you for your response. I do not get the error while write, infact the error comes while  trying to establish the connection to DB. Do you think it is the same reason that you highlighted above?

Meanwhile, what i have done is - have added a while loop for now to keep on trying to establish the connection for n number of times. But was wondering if we can fix this at the host level itself so that it does not close the connection?

**Comment by dernst** [comment]
`SIGPIPE` can occur during write operations on the socket connection (not the database). Such a write operation happens when you are sending any data to the database even if it's just "run this query for me plz 'SELECT * FROM foo'" (ofc the actual protocol is more complicated).

Most JDBC drivers allow adding extra options in the connection string. These options are vendor specific though. This is solely a JDBC problem then, so try adjusting settings for TCP keepalive or some automatic reconnection options for the Oracle JDBC driver. Maybe ask your IT or Oracle Support for help. I tried googling but can only find Oracle support pages that require a support account therefore I can't help with Oracle DBs and it's out of the scope of this bug tracker as well.

**Comment by doley25** [comment]
@dernst :+1: 

Thank you so much for your suggestions. I will revert back on any developments on the same :)

**Comment by s-u** [comment]
Note that the `SIGPIPE` can be any descriptor in the process - could be even output in R, some other package, Java process output or anything else. This can also happen when you run headless R and don't have any anything that can read the excess output.
