### ISSUE TITLE
Queries returns df with malformed column names.

### ISSUE THREAD

**Issue by erwiniank** [s-u/RJDBC#74]
Some databases didn't inform labeling information for table columns. This produces malformed data.frames with strange column names (eg: 'structure(c(" 4", " 5", "16", "17", "14", " 2", "17", ...').
I think would be better reverting the change where column names where replaced by column labels (Most databases have column names vs. fewer users use column label in their databases).

**Comment by karenne** [comment]
The same happens to me when using a connection to SAS

**Comment by dernst** [comment]
This sounds more like these databases don't implement their JDBC drivers correctly? As per the javadoc [1] "The suggested title is usually specified by the SQL AS clause. If a SQL AS is not specified, the value returned from getColumnLabel will be the same as the value returned by the getColumnName method." You're proposing to use `getColumnName` instead of `getColumnLabel` which should return the same value anyways unless you are explicitly changing the title in the query. Reverting to `getColumnName` and thus eliminating the use of labels would be cumbersome for columns that don't have  a sensible name like `select datediff (m, '20100131', '20100201') as foo` . Perhaps one might add a parameter to `fetch` to either select column names or labels.

[1] https://docs.oracle.com/javase/8/docs/api/java/sql/ResultSetMetaData.html#getColumnLabel-int-

**Comment by erwiniank** [comment]
@karenne You are right, these databases don't implement their JDBC drivers as expected to be. I am agree with your proposal!
