### ISSUE TITLE
Connecting R with Athena using RJDBC

### ISSUE THREAD

**Issue by romabhu** [s-u/RJDBC#80]
Hi,

In my R/Rshiny application, I am reading data from Athena partitioned table (partitioned on file_name). But the time time difference is huge when I am running the query directly on Athena (18 sec) and same query from R (55-60 sec).

When I checked, in R making a connection between R and Athena is taking majority of time.

Can you please help me with the solution for this? I am not getting why connection is taking so much time.

Query is :- select colA,colB,colB from table_name_1 where file_name in ('file_name1','file_name2');
table_name_1 is having records for 307 files, total record count = 261,981,772

**Comment by s-u** [comment]
Please provide a reproducible example. For large data pulls, make sure you set `block=` in `fetch()` to as large value as supported by your driver (the chunk side used by fetch is up to 512kb on one pull). The default of 2kb is very conservative because some drivers only support very small block sizes.
