### ISSUE TITLE
Adding schema parameter to dbExistsTable

### ISSUE THREAD

**Issue by chsafouane** [s-u/RJDBC#84]
Can you please add the support for the `schema` parameter in the same way that you added it in here: https://github.com/s-u/RJDBC/issues/34 for dbListTables and dbGetTables ?

**Comment by corinabioinformatic** [comment]
This topic is closed, but just for answering @chsafouane topic, now you can read with RJDBC (based on DBI) the schema:
`
# assuming you initiallize a succesfull db connection, in this case into the var "jconn"

dbListTables(conn =jconn, schema = "myschema") 

`

By default, schema parameter is NULL. 

In case you want to write a dataframe into determined schema I use: 

```

# Table to write, IMPORTANT: cannot carry dots or spaces in the columnames!!!
irisNew <- iris
# replacing dots in the columnames of the dataframe
names(irisNew) <- gsub("\\.", "_", names(irisNew))

# writing into the database
dbWriteTable(conn = jconn, 
             name ="myschema.iris",
             value =  irisNew)

```

I hope this helps, since I struggled for hours with this issue.
