### ISSUE TITLE
dbWriteTable sets char class columns to varchar(255)

### ISSUE THREAD

**Issue by paulvanoppen** [s-u/RJDBC#87]
In relation to [this](https://stackoverflow.com/questions/66864660/r-dbi-sql-server-dbwritetable-truncates-rows-field-types-parameter-does-not-w#comment118412981_66864660) SO discussion it appears that the dbWriteTable method is not capable of setting character columns to anything else but varchar(255).  While I found a workaround with the help from others, see the SO issue, it may be considerable to adjust the method such that it accepts the classes passed via the field.types parameter.

**Comment by s-u** [comment]
RJDBC pre-dates the existence of `field.types` and many other more recent additions to DBI. As [noted in the documentation](https://rforge.net/doc/packages/RJDBC/JDBCConnection-methods.html) using `dbWriteTable()` to create tables is really not recommended, because you likely want to have more control over the table creation (define keys, more specific types etc.). However, simply adding `field.types` is really easy.
